name: 'OpenAI PR Description Generator'
author: "Antoine Barthelemy <antoine@linux.com>"
description: 'A GitHub Action that generates a PR description using OpenAI.'
branding:
  icon: 'play'
  color: 'black'
inputs:
  model:
    description: 'OpenAI model in use'
    required: false
    default: "text-davinci-003"
  template:
    description: 'PR content template for OpenAI to understand what must be in the pull request description'
    required: false
    default: ""
  template-filepath:
    description: 'Path to the PULL_REQUEST_TEMPLATE.md file'
    required: false
    default: ".github/PULL_REQUEST_TEMPLATE.md"
  header:
    description: 'Intro phrase giving context to the model'
    required: false
    default: "Based on the output of the command `git diff`, could you please generate a pull request description using the provided information? Be concise. Description must follow this format:\n"
  api-key:
    description: 'OpenAI API key'
    required: true
    default: ""
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Upgrade Pip
      run: pip install --upgrade pip
      shell: bash
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Generate description
      run: python src/main.py
      shell: bash
      env:
        INPUT_TEMPLATE: ${{ inputs.template }}
        INPUT_TEMPLATE_FILEPATH: ${{ inputs.template-filepath }}
        INPUT_HEADER: ${{ inputs.header }}
        INPUT_MODEL: ${{ inputs.model }}
        OPENAI_API_KEY: ${{ inputs.api-key }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
