# action.yaml
name: 'OpenAI PR Description Generator'
description: 'A GitHub Action that generates a PR description using OpenAI.'
inputs:
  model:
    description: 'Enter the OpenAI model in use'
    required: false
    default: "text-davinci-003"
  template:
    description: 'Enter content template for OpenAI to understand what must be in the pull request description'
    required: false
  template-filepath:
    description: 'Path to the PULL_REQUEST_TEMPLATE.md file'
    required: false
  api_key:
    description: 'Enter your OpenAI API key'
    required: true
outputs:
  text:
    description: 'Generated PR Description'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.pr.outputs.text }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Generate description
      id: pr
      run: git show | python main.py
      shell: bash

