# action.yaml
name: 'openaiprdescription'
description: 'OpenAI generating PR description'
outputs:
  text:
    description: 'Generated PR Description'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.pr.outputs.text }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Generate description
      id: pr
      run: git diff HEAD^ HEAD | python main.py
      shell: bash

