name: 'OpenAI PR Description Generator'
author: "Antoine Barthelemy <antoine@linux.com>"
description: 'A GitHub Action that generates a PR description using OpenAI.'
branding:
  icon: 'play'
  color: 'black'
inputs:
  model:
    description: 'OpenAI model in use'
    required: false
    default: "text-davinci-003"
  template:
    description: 'PR content template for OpenAI to understand what must be in the pull request description'
    required: false
    default: ""
  template-filepath:
    description: 'Path to the PULL_REQUEST_TEMPLATE.md file'
    required: false
    default: ".github/PULL_REQUEST_TEMPLATE.md"
  header:
    description: 'Intro phrase giving context to the model'
    required: false
    default: "Based on the output of the command `git diff`, could you please generate a pull request description using the provided information? Be concise. Description must follow this format:\n"
  api-key:
    description: 'OpenAI API key'
    required: true
    default: ""
  github-token:
    description: 'Github Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Upgrade Pip
      run: pip install --upgrade pip
      shell: bash
    - name: Install Dependencies
      run: |
        pip install -r <(echo "aiohttp==3.8.4
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
cryptography==40.0.2
Deprecated==1.2.13
frozenlist==1.3.3
idna==3.4
multidict==6.0.4
openai==0.27.6
pycparser==2.21
PyGithub==1.58.2
PyJWT==2.7.0
PyNaCl==1.5.0
PyYAML==6.0
requests==2.30.0
tqdm==4.65.0
urllib3==2.0.2
wrapt==1.15.0
yarl==1.9.2
")
      shell: bash
    - name: Generate description
      run: python src/main.py
      shell: bash
      env:
        INPUT_TEMPLATE: ${{ inputs.template }}
        INPUT_TEMPLATE_FILEPATH: ${{ inputs.template-filepath }}
        INPUT_HEADER: ${{ inputs.header }}
        INPUT_MODEL: ${{ inputs.model }}
        OPENAI_API_KEY: ${{ inputs.api-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
