name: 'OpenAI PR Description Generator'
author: "Antoine Barthelemy <antoine@linux.com>"
description: 'A GitHub Action that generates a PR description using OpenAI.'
branding:
  icon: 'play'
  color: 'black'
inputs:
  model:
    description: 'OpenAI model in use'
    required: false
    default: "text-davinci-003"
  template:
    description: 'PR content template for OpenAI to understand what must be in the pull request description'
    required: false
    default: ""
  template-filepath:
    description: 'Path to the PULL_REQUEST_TEMPLATE.md file'
    required: false
    default: ".github/PULL_REQUEST_TEMPLATE.md"
  api-key:
    description: 'OpenAI API key'
    required: true
    default: ""
  github-token:
    description: 'Github Token'
    required: true
    default: ""
outputs:
  text:
    description: 'Text in the pull request description'
    value: ${{ steps.pr.outputs.text }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Generate description
      id: pr
      run: python src/main.py
      shell: bash
      env:
        INPUT_TEMPLATE_CONTENT: ${{ inputs.template }}
        INPUT_TEMPLATE_FILEPATH: ${{ inputs.template-filepath }}
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_MODEL: ${{ inputs.model }}
