---
preflights:
  env:
    - INPUT_TEMPLATE
    - INPUT_TEMPLATE_FILEPATH
    - INPUT_HEADER
    - INPUT_MODEL
    - OPENAI_API_KEY
    - GITHUB_TOKEN
    - GITHUB_ACTION_PATH
    - GITHUB_BRANCH
logs:
  logging: 'configuration/logging.conf'
  profile: action  # choose(dev|action)
