---
preflights:
  env:
    - GITHUB_TOKEN
    - INPUT_TEMPLATE
    - INPUT_TEMPLATE_FILEPATH
      #- INPUT_API_KEY
    - INPUT_MODEL
logs:
  logging: 'configuration/logging.conf'
  profile: dev  # choose(dev|prod)
