---
preflights:
  env:
    - GITHUB_TOKEN
    - INPUT_TEMPLATE_CONTENT
    - INPUT_TEMPLATE_FILEPATH
    - INPUT_API_KEY
    - INPUT_MODEL
logs:
  logging: 'config/logging.conf'
  profile: dev  # choose(dev|prod)
