---
preflights:
  env:
    - INPUT_TEMPLATE
    - INPUT_TEMPLATE_FILEPATH
    - INPUT_HEADER
    - INPUT_MODEL
    - OPENAI_API_KEY
    - GITHUB_TOKEN
logs:
  logging: 'configuration/logging.conf'
  profile: dev  # choose(dev|prod)
