name: Shell

on:
  push:
    paths:
      - '*.sh'

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: ./dev
        env:
          SHELLCHECK_OPTS: -s sh -e SC1091
