name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate pr description
        id: pr
        uses: ./ # Uses an action in the root directory
        with:
          api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GH_TOKEN }}
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
            #- name: Print generated pr description
            #  run: echo "${{ steps.pr.outputs.text }}"
